import { useEffect } from "react";

const HELP = {
  "Room ID": {
    meaning: "Unique identifier for the conditioned space. It is generated by the application and normally should not be edited.",
    source: "Project room schedule / architectural drawings."
  },
  "Room name": {
    meaning: "Descriptive name of the conditioned space used in schedules and reports.",
    source: "Architectural room schedule and approved floor plans."
  },
  Length: {
    meaning: "Internal room length used to calculate floor area and volume for the cooling-load model.",
    source: "Architectural drawings or coordinated BIM model."
  },
  Width: {
    meaning: "Internal room width used with length to calculate floor area and volume.",
    source: "Architectural drawings or coordinated BIM model."
  },
  Height: {
    meaning: "Conditioned-space height used to calculate room volume and support airside calculations.",
    source: "Architectural sections, reflected ceiling plans, or BIM model."
  },
  Occupants: {
    meaning: "Design occupancy for the room. Occupancy affects sensible and latent internal gains and may affect ventilation requirements.",
    source: "Project brief/room schedule; for ventilation design consult ASHRAE 62.1 or the applicable local requirement."
  },
  "Equipment allowance": {
    meaning: "Estimated sensible/latent heat contribution from plug loads and installed equipment in the room.",
    source: "Electrical equipment schedule, equipment data sheets, tenant brief; ASHRAE Handbook—Fundamentals, Chapter 18 for load-calculation principles."
  },
  "Window area": {
    meaning: "Fenestration area exposed to the conditioned space. It is used for transmission and solar heat-gain calculations.",
    source: "Architectural window schedule and elevations; ASHRAE Handbook—Fundamentals, Chapter 15 Fenestration."
  },
  "Outdoor design condition": {
    meaning: "Location-specific outdoor weather condition used as the cooling design basis.",
    source: "ASHRAE Handbook—Fundamentals, Chapter 14 Climatic Design Information, or the approved local weather/design standard."
  },
  "Cooling design percentile": {
    meaning: "Annual frequency criterion used to select the outdoor cooling design condition. The selected percentile should match the project design basis.",
    source: "ASHRAE Handbook—Fundamentals, Chapter 14 Climatic Design Information."
  },
  "Indoor dry-bulb": {
    meaning: "Target indoor dry-bulb temperature for the conditioned space at design conditions.",
    source: "Project design brief and thermal-comfort criteria; ASHRAE Standard 55 and ASHRAE Handbook—Fundamentals, Chapter 9."
  },
  "Indoor RH": {
    meaning: "Target indoor relative humidity used for psychrometric and latent-load calculations.",
    source: "Project humidity criterion; ASHRAE Standard 55 and applicable indoor-air-quality/design requirements."
  },
  "Outdoor RH for psychrometrics": {
    meaning: "Outdoor relative humidity used to define the outdoor psychrometric state. Prefer a coincident weather value associated with the selected design condition rather than an arbitrary assumption.",
    source: "ASHRAE Handbook—Fundamentals, Chapter 14 climatic data and Chapter 1 psychrometrics."
  },
  "Design margin": {
    meaning: "Additional design allowance applied after the calculated load. It should represent an explicit project engineering criterion, not a substitute for accurate inputs.",
    source: "Project design criteria and engineer judgement. ASHRAE Handbook—Fundamentals, Chapter 18 cautions against compounding safety factors."
  },
  "Zoning priority": {
    meaning: "Project preference used by the system-decision logic when comparing HVAC arrangements. It is not an ASHRAE-prescribed numerical input.",
    source: "Project requirements, architectural zoning and engineer/system-selection judgement."
  },
  "Dedicated ventilation required": {
    meaning: "Indicates whether the project requires a dedicated outdoor-air/ventilation strategy in addition to room conditioning.",
    source: "ASHRAE Standard 62.1 for applicable commercial buildings, together with the project brief and local code."
  },
  "Ceiling/service space limited": {
    meaning: "Indicates that available ceiling or service-zone depth constrains equipment and distribution selection.",
    source: "Architectural reflected ceiling plan, sections and coordinated MEP model."
  },
  "Outdoor-unit space limited": {
    meaning: "Indicates that the available external space constrains outdoor equipment selection or arrangement.",
    source: "Architectural/site drawings, equipment schedule and project coordination constraints."
  },
  "Central plant available": {
    meaning: "Indicates whether chilled-water or another central plant solution is available for the project.",
    source: "Project MEP brief, plant-room drawings and mechanical equipment schedule."
  }
};

function normalise(text) {
  return text.replace(/\s+/g, " ").trim();
}

function makeHelp(label) {
  const key = normalise(label);
  return HELP[key] || {
    meaning: `Engineering input: ${key}. Enter the project-specific value used by the calculation or selection step.`,
    source: "Use the applicable ASHRAE Handbook/Standard, SMACNA design manual where ductwork is involved, manufacturer data, approved drawings, schedules, or project design criteria. Verify the edition used by this project."
  };
}

export default function EngineeringInputHelp() {
  useEffect(() => {
    const STYLE_ID = "engineering-input-help-styles";
    if (!document.getElementById(STYLE_ID)) {
      const style = document.createElement("style");
      style.id = STYLE_ID;
      style.textContent = `
        .engineering-help-trigger{display:inline-flex;align-items:center;justify-content:center;width:17px;height:17px;margin-left:6px;border:1px solid #94a3b8;border-radius:50%;background:#fff;color:#475569;font-size:11px;font-weight:700;cursor:help;vertical-align:middle;padding:0;line-height:1}
        .engineering-help-trigger:focus{outline:2px solid #64748b;outline-offset:2px}
        .engineering-help-popover{position:fixed;z-index:9999;width:min(360px,calc(100vw - 24px));padding:12px 14px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;color:#0f172a;box-shadow:0 12px 32px rgba(15,23,42,.18);font-size:12px;line-height:1.45;pointer-events:none}
        .engineering-help-popover strong{display:block;margin-bottom:5px;font-size:13px}
        .engineering-help-popover .help-source{margin-top:7px;color:#475569}
        .engineering-help-popover .help-source b{color:#0f172a}
      `;
      document.head.appendChild(style);
    }

    let active = null;
    let popover = null;

    const close = () => {
      if (popover) popover.remove();
      popover = null;
      active = null;
    };

    const show = (trigger, label) => {
      close();
      const help = makeHelp(label);
      popover = document.createElement("div");
      popover.className = "engineering-help-popover";
      popover.innerHTML = `<strong>${label.replace(/</g, "&lt;")}</strong><div>${help.meaning.replace(/</g, "&lt;")}</div><div class="help-source"><b>Where to find it:</b> ${help.source.replace(/</g, "&lt;")}</div>`;
      document.body.appendChild(popover);
      active = trigger;
      const rect = trigger.getBoundingClientRect();
      const width = Math.min(360, window.innerWidth - 24);
      const left = Math.max(12, Math.min(rect.left, window.innerWidth - width - 12));
      const top = Math.min(window.innerHeight - popover.offsetHeight - 12, rect.bottom + 8);
      popover.style.left = `${left}px`;
      popover.style.top = `${Math.max(12, top)}px`;
    };

    const scan = () => {
      document.querySelectorAll("label").forEach((labelEl) => {
        if (labelEl.dataset.engineeringHelpAttached === "true") return;
        const text = normalise(labelEl.childNodes[0]?.textContent || labelEl.textContent || "");
        if (!text || text === "Remove") return;
        const trigger = document.createElement("button");
        trigger.type = "button";
        trigger.className = "engineering-help-trigger";
        trigger.setAttribute("aria-label", `Explain ${text}`);
        trigger.textContent = "?";
        trigger.addEventListener("mouseenter", () => show(trigger, text));
        trigger.addEventListener("focus", () => show(trigger, text));
        trigger.addEventListener("mouseleave", close);
        trigger.addEventListener("blur", close);
        labelEl.appendChild(trigger);
        labelEl.dataset.engineeringHelpAttached = "true";
      });
    };

    scan();
    const observer = new MutationObserver(scan);
    observer.observe(document.body, { childList: true, subtree: true });
    window.addEventListener("resize", close);
    window.addEventListener("scroll", close, true);
    return () => {
      observer.disconnect();
      window.removeEventListener("resize", close);
      window.removeEventListener("scroll", close, true);
      close();
      document.querySelectorAll(".engineering-help-trigger").forEach((node) => node.remove());
      document.querySelectorAll("label").forEach((node) => { delete node.dataset.engineeringHelpAttached; });
    };
  }, []);

  return null;
}
