import { buildReferenceDrivenInputs } from "../engineering/reference/referenceDrivenInputs.js";
import { applyReferenceToEngineeringInputs, buildReferenceResultTrace } from "../engineering/reference/referenceCalculationBridge.js";

export const runReferenceTraceabilityPanelTests = () => [
  { id: "REFUI-001", name: "Trace contains dataset version after explicit application", passed: (() => { const resolved = buildReferenceDrivenInputs({ locationId: "LAGOS_IKEJA", constructionId: "ASHRAE_90_1_CZ1_MASS_WALL" }); const applied = applyReferenceToEngineeringInputs({ wall: { uValueWm2K: 0.5 } }, resolved); const trace = buildReferenceResultTrace({ referenceBasis: applied.referenceBasis, referenceAppliedInputs: applied.inputs, finalInputs: applied.inputs }); return trace.explicitApplication === true && trace.referenceBasis.datasetVersion === "1.1.0"; })() },
  { id: "REFUI-002", name: "Trace exposes source record references", passed: (() => { const resolved = buildReferenceDrivenInputs({ locationId: "LAGOS_IKEJA", constructionId: "ASHRAE_90_1_CZ1_MASS_WALL" }); const applied = applyReferenceToEngineeringInputs({ wall: { uValueWm2K: 0.5 } }, resolved); return Boolean(applied.referenceBasis.location?.sourceRef) && Boolean(applied.referenceBasis.construction?.sourceRef); })() },
  { id: "REFUI-003", name: "Benchmark flag remains visible in trace basis", passed: (() => { const resolved = buildReferenceDrivenInputs({ fenestrationId: "ASHRAE_90_1_CZ1_VERTICAL_GLAZING_METAL" }); const applied = applyReferenceToEngineeringInputs({ windows: { uValueWm2K: 2.8, shgc: 0.4 } }, resolved); const trace = buildReferenceResultTrace({ referenceBasis: applied.referenceBasis, referenceAppliedInputs: applied.inputs, finalInputs: applied.inputs }); return trace.referenceBasis.fenestration.benchmarkOnly === true; })() },
  { id: "REFUI-004", name: "Engineer override is retained as final value", passed: (() => { const resolved = buildReferenceDrivenInputs({ constructionId: "ASHRAE_90_1_CZ1_MASS_WALL" }); const applied = applyReferenceToEngineeringInputs({ wall: { uValueWm2K: 0.5 } }, resolved); const finalInputs = { ...applied.inputs, wall: { ...applied.inputs.wall, uValueWm2K: 0.7 } }; const trace = buildReferenceResultTrace({ referenceBasis: applied.referenceBasis, referenceAppliedInputs: applied.inputs, finalInputs }); return trace.engineerOverrideWins === true && trace.overriddenFields[0]?.finalValue === 0.7; })() },
  { id: "REFUI-005", name: "Missing reference value remains engineer-owned", passed: (() => { const resolved = buildReferenceDrivenInputs({ constructionId: "ENGINEER_DEFINED_MASONRY_WALL" }); const applied = applyReferenceToEngineeringInputs({ wall: { uValueWm2K: 0.7 } }, resolved); return applied.inputs.wall.uValueWm2K === 0.7; })() },
  { id: "REFUI-006", name: "Trace is not created before explicit application", passed: buildReferenceResultTrace({ referenceBasis: null, referenceAppliedInputs: null, finalInputs: {} }) === null },
];
