import { createReleaseHistory, createReleaseCandidate, releaseBaseline, attachRevisionSnapshotToCandidate, supersedeReleasedBaselineForNewRevision, getReleasedBaseline, getReleaseHistorySummary, serializeReleaseHistory, deserializeReleaseHistory } from "../engineering/report/releaseControl.js";

const approvedRevisionHistory = {
  schemaVersion: "1.0",
  currentRevisionId: "REV-001",
  revisions: [{ revisionId: "REV-001", revisionNumber: 1, status: "APPROVED", approvalSnapshot: { approved: true, approver: "Engineer A", timestamp: "2026-09-09T08:00:00Z" }, packageSnapshot: { packageVersion: "24.0.0", readiness: { constructionReady: false } } }],
};

export const runReleaseControlTests = () => [
  (() => { const history = createReleaseHistory(); if (history.releases.length !== 0 || history.currentReleaseId !== null) throw new Error("REL-001 failed"); return { id: "REL-001", name: "Release history starts with no release baseline", passed: true }; })(),
  (() => { const history = createReleaseCandidate({ revisionHistory: approvedRevisionHistory, revisionId: "REV-001", releaseVersion: "1.0.0", createdBy: "Engineer A", createdAt: "2026-09-09T09:00:00Z", reason: "First production release" }); const candidate = history.releases[0]; if (candidate.releaseId !== "REL-001" || candidate.status !== "RELEASE_CANDIDATE" || candidate.revisionId !== "REV-001") throw new Error("REL-002 failed"); return { id: "REL-002", name: "Only an approved revision can become a release candidate", passed: true }; })(),
  (() => { let failed = false; try { createReleaseCandidate({ revisionHistory: { ...approvedRevisionHistory, revisions: [{ ...approvedRevisionHistory.revisions[0], status: "DRAFT" }] }, revisionId: "REV-001", releaseVersion: "1.0.0", createdBy: "Engineer A", createdAt: "2026-09-09T09:00:00Z", reason: "Invalid release" }); } catch { failed = true; } if (!failed) throw new Error("REL-003 failed"); return { id: "REL-003", name: "Unapproved revisions cannot enter release management", passed: true }; })(),
  (() => { let history = createReleaseCandidate({ revisionHistory: approvedRevisionHistory, revisionId: "REV-001", releaseVersion: "1.0.0", createdBy: "Engineer A", createdAt: "2026-09-09T09:00:00Z", reason: "First production release" }); history = attachRevisionSnapshotToCandidate({ releaseHistory: history, releaseId: "REL-001", revisionSnapshot: approvedRevisionHistory.revisions[0].packageSnapshot }); history = releaseBaseline({ releaseHistory: history, releaseId: "REL-001", releasedBy: "Release Manager", releasedAt: "2026-09-09T10:00:00Z", releaseReason: "Approved production baseline", releaseEvidenceReference: "APP-001", productionCommitSHA: "abc123" }); const released = getReleasedBaseline(history); if (released.status !== "RELEASED" || released.productionCommitSHA !== "abc123" || released.baselineSnapshot?.revisionId !== "REV-001") throw new Error("REL-004 failed"); return { id: "REL-004", name: "Released baseline records immutable release metadata and production commit", passed: true }; })(),
  (() => { let failed = false; try { releaseBaseline({ releaseHistory: createReleaseCandidate({ revisionHistory: approvedRevisionHistory, revisionId: "REV-001", releaseVersion: "1.0.0", createdBy: "Engineer A", createdAt: "2026-09-09T09:00:00Z", reason: "First production release" }), releaseId: "REL-001", releasedBy: "Release Manager", releasedAt: "2026-09-09T10:00:00Z", releaseReason: "Release", releaseEvidenceReference: "APP-001", productionCommitSHA: "" }); } catch { failed = true; } if (!failed) throw new Error("REL-005 failed"); return { id: "REL-005", name: "Production release requires an explicit production commit SHA", passed: true }; })(),
  (() => { let history = createReleaseCandidate({ revisionHistory: approvedRevisionHistory, revisionId: "REV-001", releaseVersion: "1.0.0", createdBy: "Engineer A", createdAt: "2026-09-09T09:00:00Z", reason: "First production release" }); history = attachRevisionSnapshotToCandidate({ releaseHistory: history, releaseId: "REL-001", revisionSnapshot: approvedRevisionHistory.revisions[0].packageSnapshot }); history = releaseBaseline({ releaseHistory: history, releaseId: "REL-001", releasedBy: "Release Manager", releasedAt: "2026-09-09T10:00:00Z", releaseReason: "Approved production baseline", releaseEvidenceReference: "APP-001", productionCommitSHA: "abc123" }); const changed = supersedeReleasedBaselineForNewRevision({ releaseHistory: history, newRevisionId: "REV-002", changedAt: "2026-09-09T11:00:00Z" }); if (changed.releases[0].status !== "SUPERSEDED" || changed.releases[0].supersededByRevisionId !== "REV-002") throw new Error("REL-006 failed"); return { id: "REL-006", name: "A new design revision supersedes the prior production baseline", passed: true }; })(),
  (() => { const history = createReleaseCandidate({ revisionHistory: approvedRevisionHistory, revisionId: "REV-001", releaseVersion: "1.0.0", createdBy: "Engineer A", createdAt: "2026-09-09T09:00:00Z", reason: "First production release" }); const restored = deserializeReleaseHistory(serializeReleaseHistory(history)); const summary = getReleaseHistorySummary(restored); if (summary.releaseCount !== 1 || summary.candidateCount !== 1 || summary.currentReleaseId !== "REL-001") throw new Error("REL-007 failed"); return { id: "REL-007", name: "Release history is serializable and traceable", passed: true }; })(),
];
