import { createReleaseAudit, recordReleaseAuditEvent, serializeReleaseAudit, deserializeReleaseAudit, getReleaseAuditFor } from "../engineering/report/releaseAudit.js";

export const runReleaseAuditTests = () => [
  (() => { const h = createReleaseAudit(); if (h.events.length !== 0) throw new Error("AUD-001 failed"); return { id: "AUD-001", name: "Release audit history initializes cleanly", passed: true }; })(),
  (() => { const h = recordReleaseAuditEvent({ eventType: "RELEASED", releaseId: "REL-001", revisionId: "REV-001", actor: "Release Manager", timestamp: "2026-09-09T10:00:00Z", evidenceReference: "APP-001", productionCommitSHA: "abc123" }); if (h.events[0].eventId !== "AUDIT-0001" || h.events[0].productionCommitSHA !== "abc123") throw new Error("AUD-002 failed"); return { id: "AUD-002", name: "Release events record accountable actor, evidence and commit", passed: true }; })(),
  (() => { let failed = false; try { recordReleaseAuditEvent({ eventType: "INVALID", releaseId: "REL-001", revisionId: "REV-001", actor: "Engineer", timestamp: "2026-09-09T10:00:00Z" }); } catch { failed = true; } if (!failed) throw new Error("AUD-003 failed"); return { id: "AUD-003", name: "Unsupported audit event types are rejected", passed: true }; })(),
  (() => { const h = recordReleaseAuditEvent({ eventType: "RELEASED", releaseId: "REL-001", revisionId: "REV-001", actor: "Manager", timestamp: "2026-09-09T10:00:00Z" }); const h2 = recordReleaseAuditEvent({ auditHistory: h, eventType: "PROMOTION_RECORDED", releaseId: "REL-001", revisionId: "REV-001", actor: "Manager", timestamp: "2026-09-09T10:05:00Z", productionCommitSHA: "abc123" }); if (getReleaseAuditFor(h2, "REL-001").length !== 2) throw new Error("AUD-004 failed"); return { id: "AUD-004", name: "Audit events remain linked to the release and revision", passed: true }; })(),
  (() => { const h = recordReleaseAuditEvent({ eventType: "RELEASED", releaseId: "REL-001", revisionId: "REV-001", actor: "Manager", timestamp: "2026-09-09T10:00:00Z" }); const restored = deserializeReleaseAudit(serializeReleaseAudit(h)); if (restored.events.length !== 1 || restored.events[0].eventType !== "RELEASED") throw new Error("AUD-005 failed"); return { id: "AUD-005", name: "Audit trail is serializable and restorable", passed: true }; })(),
];
