import { createRevisionHistory, createRevision, recordRevisionApproval, updateRevisionStatus, getCurrentRevision, getRevisionHistorySummary, serializeRevisionHistory, deserializeRevisionHistory } from "../engineering/report/revisionControl.js";

const basePackage = { packageVersion: "22.0.0", engineeringApproval: { status: "PENDING", approved: false }, readiness: { engineeringApprovalStatus: "PENDING", constructionReady: false } };

export const runRevisionControlTests = () => [
  (() => { const history = createRevisionHistory({ packageData: basePackage, changedBy: "Engineer A", changedAt: "2026-09-09T08:00:00Z", reason: "Initial design package" }); if (history.currentRevisionId !== "REV-001" || history.revisions.length !== 1 || history.revisions[0].status !== "DRAFT") throw new Error("REV-001 failed"); return { id: "REV-001", name: "Initial revision is created with accountable metadata", passed: true }; })(),
  (() => { const history = createRevisionHistory({ packageData: basePackage, changedBy: "Engineer A", changedAt: "2026-09-09T08:00:00Z" }); const next = createRevision({ history, packageData: { ...basePackage, packageVersion: "24.0.0", engineeringApproval: { status: "APPROVED", approved: true } }, changedBy: "Engineer A", changedAt: "2026-09-09T09:00:00Z", reason: "Updated room load inputs", affected: { rooms: ["R1"], calculations: ["COOLING_LOAD"], equipment: ["AC-01"], ducts: ["D-01"] } }); const previous = next.revisions.find((item) => item.revisionId === "REV-001"); const current = getCurrentRevision(next); if (next.currentRevisionId !== "REV-002" || previous.status !== "SUPERSEDED" || current.status !== "DRAFT" || !current.approvalInvalidated || current.packageSnapshot.engineeringApproval.approved || current.packageSnapshot.readiness.engineeringApprovalStatus !== "PENDING" || previous.packageSnapshot.packageVersion !== "22.0.0") throw new Error("REV-002 failed"); return { id: "REV-002", name: "Design change creates a new revision and invalidates approval", passed: true }; })(),
  (() => { const history = createRevisionHistory({ packageData: basePackage, changedBy: "Engineer A", changedAt: "2026-09-09T08:00:00Z" }); const review = updateRevisionStatus({ history, revisionId: "REV-001", status: "IN_REVIEW" }); if (getCurrentRevision(review).status !== "IN_REVIEW") throw new Error("REV-003 review transition failed"); const approved = recordRevisionApproval({ history: review, revisionId: "REV-001", packageData: { ...basePackage, engineeringApproval: { status: "APPROVED", approved: true } }, approval: { approved: true, approver: "Engineer A", timestamp: "2026-09-09T10:00:00Z", evidenceReference: "REV-001" } }); const current = getCurrentRevision(approved); if (current.status !== "APPROVED" || !current.approvalSnapshot?.approved || current.packageSnapshot.engineeringApproval.approved) throw new Error("REV-003 approval snapshot failed"); return { id: "REV-003", name: "Approval is stored separately from the immutable design snapshot", passed: true }; })(),
  (() => { const history = createRevisionHistory({ packageData: basePackage, changedBy: "Engineer A", changedAt: "2026-09-09T08:00:00Z" }); const summary = getRevisionHistorySummary(history); if (summary.revisionCount !== 1 || summary.currentRevisionId !== "REV-001" || summary.currentStatus !== "DRAFT") throw new Error("REV-004 failed"); return { id: "REV-004", name: "Revision history summary is traceable", passed: true }; })(),
  (() => { const history = createRevisionHistory({ packageData: basePackage, changedBy: "Engineer A", changedAt: "2026-09-09T08:00:00Z" }); const restored = deserializeRevisionHistory(serializeRevisionHistory(history)); if (restored.currentRevisionId !== history.currentRevisionId || restored.revisions.length !== 1) throw new Error("REV-005 failed"); return { id: "REV-005", name: "Revision history can be serialized and restored", passed: true }; })(),
  (() => { let failed = false; try { createRevisionHistory({ packageData: basePackage, changedBy: "", changedAt: "2026-09-09T08:00:00Z" }); } catch { failed = true; } if (!failed) throw new Error("REV-006 failed"); return { id: "REV-006", name: "Revision creation requires accountable change metadata", passed: true }; })(),
];
